<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework 3</span></h1>
</div>
<div class="row">
    <?php if(count($posts) > 0): ?>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($posts as $post): ?>
                    <tr>
                        <td><?= $post->getId(); ?></td>
                        <td><?= $post->getTitle(); ?></td>
                        <td><?= $post->getDescription(); ?></td>
                        <td><?= $post->getCategory(); ?></td>
                        <td><a href="#" class="btn btn-primary">View</a></td>
                        <td><a href="#" class="btn btn-warning">Update</a></td>
                        <td><a href="#" class="btn btn-danger">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div>No record found</div>
    <?php endif; ?>
</div>
